CREATE DATABASE StoreDB;
USE StoreDB;
CREATE TABLE Product (ID INT, ProductName VARCHAR(50), Category VARCHAR(50), Price INT);
INSERT INTO Product VALUES (1, 'Keyboard', 'Computer', 2500), (2, 'Mouse', 'Computer', 1500), (3, 'Monitor', 'Computer', 25000), (4, 'Printer', 'Computer', 18000), (5, 'Headphones', 'Accessories', 3500), (6, 'Webcam', 'Accessories', 5000), (7, 'Laptop', 'Computer', 85000), (8, 'USB Cable', 'Accessories', 800), (9, 'SSD', 'Storage', 12000), (10, 'Hard Disk', 'Storage', 18000), (11, 'RAM', 'Computer', 10000), (12, 'Speaker', 'Accessories', 4500);
SELECT * FROM Product WHERE Category = 'Computer' AND Price > 20000;
SELECT * FROM Product WHERE Category = 'Accessories' AND Price < 5000;
SELECT * FROM Product WHERE Price > 5000 AND Price < 20000;
SELECT ProductName, Price FROM Product WHERE Category = 'Storage' AND Price > 15000;
SELECT * FROM Product WHERE Category IN ('Computer', 'Storage');
SELECT * FROM Product WHERE Price < 2000 OR Price > 50000;
SELECT * FROM Product WHERE ProductName IN ('Keyboard', 'Mouse');
SELECT * FROM Product WHERE Category IN ('Accessories', 'Storage') AND Price > 5000;
SELECT * FROM Product WHERE Category IN ('Computer', 'Storage', 'Accessories');
SELECT * FROM Product WHERE ID IN (1, 4, 7, 10);
SELECT * FROM Product WHERE Price IN (1500, 3500, 5000, 10000);
SELECT * FROM Product WHERE Category IN ('Computer', 'Storage') AND Price > 15000;
SELECT * FROM Product WHERE Price > 10000;
SELECT * FROM Product WHERE Price <= 5000;
SELECT * FROM Product WHERE Price >= 12000 AND Price <= 25000;
SELECT * FROM Product WHERE ID > 5 AND Price < 20000;
SELECT * FROM Product WHERE Category <> 'Accessories';
SELECT * FROM Product WHERE Price <> 18000;
SELECT * FROM Product WHERE Category <> 'Computer' AND Price > 10000;
SELECT * FROM Product WHERE Price <> 5000 OR Category = 'Storage';
UPDATE Product SET Price = Price + 1000 WHERE Category = 'Accessories' AND Price < 5000;
UPDATE Product SET Price = Price + 5000 WHERE Category = 'Computer' AND Price < 30000;
UPDATE Product SET Price = 15000 WHERE ProductName = 'SSD' AND Category = 'Storage';
UPDATE Product SET Price = Price + 500 WHERE Category IN ('Accessories', 'Storage');
UPDATE Product SET Price = 2000 WHERE Price IN (1500, 2500);
UPDATE Product SET Category = 'Computer' WHERE Category IN ('Accessories', 'Storage') AND ID > 8;
UPDATE Product SET Price = Price + 1000 WHERE Category IN ('Computer', 'Storage');
UPDATE Product SET Price = 5000 WHERE ID IN (2, 5, 6, 12);
UPDATE Product SET Category = 'Accessories' WHERE ID IN (3, 9, 11);
DELETE FROM Product WHERE Category = 'Accessories' AND Price < 2000;
DELETE FROM Product WHERE Category = 'Computer' AND Price > 80000;
DELETE FROM Product WHERE ProductName = 'USB Cable' AND Category = 'Accessories';
DELETE FROM Product WHERE Category IN ('Storage', 'Accessories');
DELETE FROM Product WHERE Price < 1000 OR Price > 80000;
DELETE FROM Product WHERE ID IN (2, 8);
DELETE FROM Product WHERE Category IN ('Computer', 'Storage');
DELETE FROM Product WHERE ID IN (1, 5, 7, 11);
DELETE FROM Product WHERE ProductName IN ('Mouse', 'Webcam', 'Speaker');
SELECT * FROM Product WHERE Category IN ('Computer', 'Storage') AND Price > 10000 AND Price <> 18000;
SELECT * FROM Product WHERE Category IN ('Accessories', 'Storage') AND Price BETWEEN 3000 AND 20000;
SELECT * FROM Product WHERE ID IN (2, 4, 6, 8, 10) AND Category <> 'Computer';
UPDATE Product SET Price = Price + 2000 WHERE Category IN ('Computer', 'Storage') AND Price < 20000 AND ID <> 4;
DELETE FROM Product WHERE Category = 'Accessories' OR Price < 1000;
SELECT * FROM Product WHERE Category IN ('Computer', 'Storage', 'Accessories') AND Price >= 5000;
UPDATE Product SET Price = 10000 WHERE Category IN ('Computer', 'Storage') AND Price < 12000;
SELECT * FROM Product WHERE Price > 5000 AND Category IN ('Computer', 'Storage');